import { Poppins } from "next/font/google";
import "./globals.css";
import Header from "@/../components/layout/header/header";
import Initializer from "@/../utils/initializer/initializer";

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: [
    "300",
    "400",
    "500",
    "600",
    "700",
    "800"
  ],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${poppins.variable}`}>
        <Header />
        {children}

        <Initializer />
      </body>
    </html>
  );
}
