import { Inter, Montserrat } from "next/font/google";
import "./globals.css";
import Header from "@/../components/layout/header/header";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
  weight: [
    "400",
    "500",
    "600",
    "700",
    "800"
  ],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.variable} ${montserrat.variable}`}>
        <Header />
        {children}
      </body>
    </html>
  );
}
